import Conversation from "../models/conversation.model.js";
import Message from "../models/message.model.js";

export const sendMessage = async (req, res) => {
    try {
        const { message } = req.body;
        const {id:receiverId} = req.params;
        const senderId = req.user._id;

        let conversation = await Conversation.findOne({
            participants: { $all: [senderId, receiverId] },
        });

        // there is no existing conversation, so create a new one
        if(!conversation){
            conversation = await Conversation.create({
                participants: [senderId, receiverId],
            });
        }

        const newMessage = await Message.create({
            senderId,
            receiverId,
            message,
        })

        // if successfully created, add the message to the conversation
        if(newMessage){
            conversation.messages.push(newMessage._id);
        }

        // this will run the save operations in parallel, ensuring data consistency
        await Promise.all([conversation.save(), newMessage.save()]);

        res.status(201).json(newMessage);

    } catch (error) {
        console.log(error.message);
        res.status(500).json({ message: "internal server error" });

    }
}


export const getMessages = async (req, res) => {
    try {
        const {id:userToChatId} = req.params;
        const senderId = req.user._id;

        const conversation = await Conversation.findOne({participants: { $all: [senderId, userToChatId] }  }).populate('messages');

        if(!conversation){
            return res.status(200).json([]);
        }

        const messages = conversation.messages;

        res.status(200).json(messages);

    } catch (error) {
        console.log(error.message);
        res.status(500).json({ message: "internal server error" });

    }
}